name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Buildozer in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd -w /home/user/hostcwd kivy/buildozer buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk

