name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev automake
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        run: |
          sudo apt install -y default-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O android_cmdline_tools.zip
          unzip android_cmdline_tools.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/bin $HOME/android-sdk/cmdline-tools/latest/
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$HOME/android-sdk/build-tools" >> $GITHUB_ENV
          echo "export PATH=$PATH:$HOME/android-sdk/tools:$HOME/android-sdk/tools/bin" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Handle Java path
        run: |
          export JAVA_HOME=/usr/lib/jvm/default-java
          export PATH=$JAVA_HOME/bin:$PATH
          buildozer -v android debug --accept-license  # No `yes` command used

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk

